### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by pawamoy** [houbie/pyprojectx#8]
Damn, you make a good point:

> Adding tools as dev dependencies impacts your production dependencies and can even lead to unresolvable conflicts

However I wonder: since the tools are installed in isolation, they don't have access to the production dependencies? How do I run tests if they import production libraries?

**Comment by pawamoy** [comment]
Hmmmm, I think I got it. When you say "tools", you mean Poetry, PDM, etc.
But then you still add libraries, like pytest, as dev-dependencies. OK.

**Comment by houbie** [comment]
Exactly :)

**Comment by pawamoy** [comment]
🙂 

And then tools that only need to read the code, like flake8, can also be managed by your project. Very interesting 😄
